doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
        
#        driver: '%env(DATABASE_DRIVER)%'
#        host: '%env(POSTGRES_HOST)%'
#        port: '%env(POSTGRES_PORT)%'
#        user: '%env(POSTGRES_USER)%'
#        password: '%env(POSTGRES_PASSWORD)%'
#        dbname: '%env(POSTGRES_DB)%'
#        server_version: '%env(POSTGRES_VERSION)%'


        driver: '%env(DATABASE_DRIVER)%'
        host: '%env(MYSQL_HOST)%'
        port: '%env(MYSQL_PORT)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASSWORD)%'
        dbname: '%env(MYSQL_DATABASE)%'
        server_version: '%env(MYSQL_VERSION)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppTelegram:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Telegram'
                prefix: 'App\Entity\Telegram'
                alias: AppTelegram
            AppFeedback:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Feedback'
                prefix: 'App\Entity\Feedback'
                alias: AppFeedback
            AppUser:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/User'
                prefix: 'App\Entity\User'
                alias: AppUser
            AppMessenger:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Messenger'
                prefix: 'App\Entity\Messenger'
                alias: AppMessenger

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

            driver: '%env(DATABASE_DRIVER)%'
            host: '%env(MYSQL_HOST)%'
            port: '%env(MYSQL_PORT)%'
            user: '%env(MYSQL_USER)%'
            password: '%env(MYSQL_PASSWORD)%'
#            important: name should be different
            dbname: '%env(MYSQL_DATABASE)%_test'
            server_version: '%env(MYSQL_VERSION)%'

#            todo: use pdo_sqlite (then delete app_test, when DB::insertRequest replaced)
#            driver: pdo_sqlite
#            path: "%kernel.cache_dir%/test_%env(TEST_TOKEN)%.db"
#            url: 'sqlite3:///:memory:'
            logging: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
