doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
  #        server_version: '8'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      AppTelegram:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Telegram'
        prefix: 'App\Entity\Telegram'
        alias: AppTelegram
      AppFeedback:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Feedback'
        prefix: 'App\Entity\Feedback'
        alias: AppFeedback
      AppUser:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/User'
        prefix: 'App\Entity\User'
        alias: AppUser
      AppMessenger:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Messenger'
        prefix: 'App\Entity\Messenger'
        alias: AppMessenger
      AppIntl:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/Intl'
        prefix: 'App\Entity\Intl'
        alias: AppAddress

when@test:
  doctrine:
    dbal:
      #      default_table_options:
      #        charset: utf8mb4
      #        collation: utf8mb4_0900_as_cs
      #        collate: utf8mb4_0900_as_cs
      #        engine: InnoDB
      # "TEST_TOKEN" is typically set by ParaTest
      #            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

      #            todo: use pdo_sqlite (then delete app_test, when DB::insertRequest replaced)
      #            driver: pdo_sqlite
      #            path: "%kernel.cache_dir%/test_%env(TEST_TOKEN)%.db"
      #            url: 'sqlite3:///:memory:'
      logging: true

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
