monolog:
  channels:
    - activities

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: warning
        channels: [ "!event" ]
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!console" ]
      activity:
        type: telegram
        token: '%app.telegram_activities_token%'
        channel: '%app.telegram_activities_channel%'
        level: debug
        channels: [ 'activities' ]
      error:
        type: telegram
        token: '%app.telegram_errors_token%'
        channel: '%app.telegram_errors_channel%'
        level: warning

when@test:
  monolog:
    handlers:
      main:
        type: test
        level: debug
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        buffer_size: 50
      nested:
        type: stream
        path: php://stderr
        level: warning
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]
      error:
        type: telegram
        token: '%app.telegram_errors_token%'
        channel: '%app.telegram_errors_channel%'
        level: warning
