version: "3.5"

services:
  php:
    build:
      context: .
      target: php
    ports: [ '8000:8000' ]
    volumes:
      - .:/var/task
    environment:
      HANDLER: public/index.php

###> doctrine/doctrine-bundle ###
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: app
      MYSQL_PASSWORD: 1111
      MYSQL_PORT: 3306
      MYSQL_VERSION: 8
    volumes:
      - mysql-data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  mysql-data:
###< doctrine/doctrine-bundle ###