# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: symfony

provider:
  name: aws
  # The AWS region in which to deploy (us-east-1 is the default)
  region: us-east-1
  # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
  stage: dev
  runtime: provided.al2
  environment:
    # Symfony environment variables
    #should be synced with:
    #1) .env
    #1) phpunit.xml
    #2) serverless.yml
    APP_STAGE: dev
    APP_ENV: prod
    APP_SECRET: ${ssm:/feedbacks/${sls:stage}/APP_SECRET}
#    todo: change WEB_BASE_URL -> SITE_BASE_URL
    SITE_BASE_URL: ${ssm:/feedbacks/${sls:stage}/WEB_BASE_URL}
    TELEGRAM_WEBHOOK_BASE_URL: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_WEBHOOK_BASE_URL}
    TELEGRAM_FEEDBACKS_USERNAME: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_USERNAME}
    TELEGRAM_FEEDBACKS_API_TOKEN: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_API_TOKEN}
    TELEGRAM_FEEDBACKS_ADMIN_IDS: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_ADMIN_IDS}
    TELEGRAM_FEEDBACKS_LANGUAGE_CODES: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_LANGUAGE_CODES}
    TELEGRAM_FEEDBACKS_ADMIN_CHAT_IDS: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_ADMIN_CHAT_IDS}
    TELEGRAM_FEEDBACKS_CHECK_UPDATE_DUPLICATES: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_CHECK_UPDATE_DUPLICATES}
    TELEGRAM_FEEDBACKS_CHECK_REQUESTS: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_CHECK_REQUESTS}
    TELEGRAM_FEEDBACKS_PROCESS_ADMIN_ONLY: ${ssm:/feedbacks/${sls:stage}/TELEGRAM_FEEDBACKS_PROCESS_ADMIN_ONLY}
    FEEDBACK_CREATOR_USER_TARGET_MESSENGER_REQUIRED: ${ssm:/feedbacks/${sls:stage}/FEEDBACK_CREATOR_USER_TARGET_MESSENGER_REQUIRED}
    DATABASE_URL: ${ssm:/feedbacks/${sls:stage}/DATABASE_URL}
    # todo: add vpc with private (for RDS) and public (lambda outbound internet requests) subnets
    # @see https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html#Add_IGW_Attach_Gateway
#  vpc:
#    securityGroupIds:
#      - sg-088db27809d621bd6
#    subnetIds:
#      - subnet-0bdb3047343de2025
#      - subnet-0c3d57c4a615a8edb
#      - subnet-050cb8e506d3b0f5b
#      - subnet-04680c5f9ee08979b
#      - subnet-01583ad711e36973c
#      - subnet-0c5933ad81e7f772b

plugins:
  - ./vendor/bref/bref

functions:
  # This function runs the Symfony website/API
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - httpApi: '*'
#      - schedule:
#          rate: rate(5 minutes)
#          input:
#            warmer: true
  # This function let us run console commands in Lambda
  console:
    handler: bin/console
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-82} # PHP
      - ${bref:layer.console} # The "console" layer

package:
  patterns:
    # Excluded files and folders for deployment
    - '!assets/**'
    - '!node_modules/**'
    - '!public/build/**'
    - '!tests/**'
    - '!var/**'
    # If you want to include files and folders that are part of excluded folders,
    # add them at the end
    - 'var/cache/prod/**'
    - 'public/build/entrypoints.json'
    - 'public/build/manifest.json'
